apiVersion: apps/v1
kind: Deployment
metadata:
  name: cedar-listener
spec:
  selector:
    matchLabels:
      app: cedar-listener
  replicas: 1
  template:
    metadata:
      labels:
        app: cedar-listener
    spec:
      containers:
        - name: cedar-listener
          image: cedarcr.azurecr.io/cedar-listener:v1
          imagePullPolicy: Always
          env:
            - name: STREAM_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: cedar-secret
                  key: stream_connectionstring
            - name: COSMOSDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cedar-secret
                  key: cosmosdb_password
            - name: COSMOSDB_CONTACT_POINT
              valueFrom:
                configMapKeyRef:
                  name: cedar-config
                  key: cosmos_contact_point
            - name: COSMOSDB_PORT
              valueFrom:
                configMapKeyRef:
                  name: cedar-config
                  key: cosmos_port
            - name: COSMOSDB_USER
              valueFrom:
                configMapKeyRef:
                  name: cedar-config
                  key: cosmos_username
          readinessProbe:
            httpGet:
              port: 8080
              path: /status
            periodSeconds: 20
          livenessProbe:
            httpGet:
              port: 8080
              path: /status
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
